[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = ">= 3.10"
karp = "^7"
xlsxwriter = ">= 3.2.2"
lark = ">= 1.2.2"
nltk = ">= 3.9.1"
typer = ">= 0.12.3"

[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"



